dag:
  conf:
    task_parallelism: 1
  parties:
  - party_id:
    - '9999'
    role: guest
  - party_id:
    - '10000'
    role: host
  - party_id:
    - '10001'
    role: arbiter
  party_tasks:
    guest_9999:
      conf:
        test_reader_guest: 2
      parties:
      - party_id:
        - '9999'
        role: guest
      tasks:
        reader_0:
          inputs:
            parameters:
              delimiter: ','
              dtype: float32
              format: csv
              id_name: id
              label_name: y
              label_type: float32
              path: file:///data/projects/fate/examples/data/breast_hetero_guest.csv
    host_10000:
      conf:
        test_reader_guest: 2
      parties:
      - party_id:
        - '10000'
        role: host
      tasks:
        reader_0:
          inputs:
            parameters:
              delimiter: ','
              dtype: float32
              format: csv
              id_name: id
              label_name: null
              path: file:///data/projects/fate/examples/data/breast_hetero_host.csv
  scheduler_party_id: '10001'
  stage: train
  tasks:
    evaluation_0:
      component_ref: evaluation
      dependent_tasks:
      - lr_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: train_output_data
              producer_task: lr_0
              roles:
              - guest
      parties:
      - party_id:
        - '9999'
        role: guest
      stage: default
    intersection_0:
      component_ref: intersection
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: reader_0
        parameters:
          method: raw
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        role: host
      stage: default
    intersection_1:
      component_ref: intersection
      dependent_tasks:
      - reader_0
      inputs:
        artifacts:
          input_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: reader_0
        parameters:
          method: raw
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        role: host
      stage: default
    lr_0:
      component_ref: hetero_lr
      dependent_tasks:
      - intersection_0
      inputs:
        artifacts:
          train_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: intersection_0
              roles:
              - guest
              - host
          validate_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: intersection_0
              roles:
              - guest
              - host
        parameters:
          batch_size: 100
          learning_rate: 0.01
          max_iter: 1
    reader_0:
      component_ref: reader
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '10000'
        role: host
      stage: default
schema_version: 2.0.0.alpha
