site_name: FATE Flow
repo_name: FederatedAI/FATE-Flow
repo_url: https://github.com/FederatedAI/FATE-Flow
edit_uri: edit/master/doc
docs_dir: doc
copyright: © Copyright 2022 WeBank Co., Ltd. | All Rights Reserved.

nav:
  - Home: index.md
  - Docs:
    #- ... | flat | *.md
    - document_navigation.md
    - fate_flow.md
    - fate_flow_data_access.md
    - fate_flow_component_registry.md
    - fate_flow_job_scheduling.md
    - fate_flow_resource_management.md
    - fate_flow_tracking.md
    - fate_flow_monitoring.md
    - fate_flow_model_registry.md
    - fate_flow_authority_management.md
    - fate_flow_server_operation.md
    - fate_flow_service_registry.md
    - fate_flow_model_migration.md
    - fate_flow_client.md
    - fate_flow_http_api.md
    - configuration_instruction.md
    - system_operational.md
    - faq.md
  - API: swagger

theme:
  name: material
  custom_dir: "doc/mkdocs/theme"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - render_swagger
  - i18n:
      default_language: en
      languages:
        zh: 中文
  - markdown-include-snippet:
      base_path: doc

markdown_extensions:
  - pymdownx.snippets:
      base_path: doc
  - mdx_math
  - admonition
  - pymdownx.highlight
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

extra:
  alternate:
    - name: English
      lang: en
      link: ""
    - name: 中文
      lang: zh
      link: "zh/"
  version:
    provider: mike

extra_css:
  - 'mkdocs/css/termynal.css'
  - 'mkdocs/css/custom.css'
  - 'mkdocs/css/extra.css'
  - 'mkdocs/css/landing.css'

extra_javascript:
  - 'mkdocs/js/termynal.js'
  - 'mkdocs/js/custom.js'
  - 'mkdocs/js/lottie-player.js'
