DEFAULT_HTTP_HOST = "127.0.0.1"
DEFAULT_HTTP_PORT = 9380
DEFAULT_PROTOCOL = "http"

DEFAULT_API_VERSION = None

DEFAULT_TIMEOUT_SECONDS = 60
REQUEST_TRY_TIMES = 3
REQUEST_MAX_WAIT_SEC = 300
REQUEST_WAIT_SEC = 2
FATE_FLOW_SERVICE_NAME = "fateflow"