# resource
job_cores: 4
computing_partitions: 8
task_run:
  spark:
    num-executors: 2
    executor-cores: 2
  eggroll:
    cores: 4
  standalone:
    cores: 4
task_timeout: 259200 # s
remote_request_timeout: 30000  # ms
federated_command_trys: 3
auto_retries: 0
sync_type: callback # poll or callback
task_device:
  type: CPU
