# resource
job_cores: 4
computing_partitions: 8
task_run:
  spark:
    num-executors: 2
    executor-cores: 2
  eggroll:
    eggroll.session.processors.per.node: 4
  standalone:
    cores: 4
job_timeout: 259200 # s
remote_request_timeout: 30000  # ms
federated_command_trys: 3
auto_retries: 0
sync_type: callback # poll or callback
task_logger:
  type: flow
  metadata:
    level: DEBUG
    debug_mode: true
task_device:
  type: CPU
launcher:
  deepspeed:
    timeout: 21600 # s
    world_size: 2
