dag:
  conf:
    model_warehouse:
      model_id: '202308211824193580540'
      model_version: '0'
  parties:
  - party_id:
    - '9999'
    role: guest
  - party_id:
    - '9998'
    role: host
  - party_id:
    - '9998'
    role: arbiter
  party_tasks:
    guest_9999:
      parties:
      - party_id:
        - '9999'
        role: guest
      tasks:
        psi_0:
          inputs:
            data:
              input_data:
                data_warehouse:
                  name: breast_hetero_guest
                  namespace: experiment
                  roles:
                  - guest
    host_9998:
      parties:
      - party_id:
        - '9998'
        role: host
      tasks:
        psi_0:
          inputs:
            data:
              input_data:
                data_warehouse:
                  name: breast_hetero_host
                  namespace: experiment
                  roles:
                  - host
  stage: predict
  tasks:
    lr_0:
      component_ref: coordinated_lr
      dependent_tasks:
      - selection_0
      inputs:
        data:
          test_data:
            task_output_artifact:
              output_artifact_key: test_output_data
              producer_task: selection_0
              roles:
              - guest
              - host
        model:
          input_model:
            model_warehouse:
              output_artifact_key: output_model
              producer_task: lr_0
              roles:
              - guest
              - host
      parameters:
        batch_size: null
        early_stop: diff
        epochs: 10
        init_param:
          fit_intercept: true
          method: zeros
        learning_rate_scheduler:
          method: linear
          scheduler_params:
            start_factor: 0.7
            total_iters: 100
        optimizer:
          alpha: 0.001
          method: SGD
          optimizer_params:
            lr: 0.1
          penalty: l2
        output_cv_data: true
        threshold: 0.5
        tol: 0.0001
    psi_0:
      component_ref: psi
      inputs:
        data: {}
      parameters: {}
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '9998'
        role: host
      stage: default
    selection_0:
      component_ref: hetero_feature_selection
      dependent_tasks:
      - psi_0
      inputs:
        data:
          test_data:
            task_output_artifact:
              output_artifact_key: output_data
              producer_task: psi_0
        model:
          input_model:
            model_warehouse:
              output_artifact_key: train_output_model
              producer_task: selection_0
      parameters:
        iv_param:
          filter_type: threshold
          metrics: iv
          threshold: 0.1
        keep_one: true
        manual_param: null
        method:
        - iv
        select_col: null
        statistic_param: null
        use_anonymous: false
      parties:
      - party_id:
        - '9999'
        role: guest
      - party_id:
        - '9998'
        role: host
schema_version: 2.0.0.alpha
